add_newline = false

[character]
success_symbol = "[](bold black)"
error_symbol = "[](bold red)"

[package]
disabled = true

[nodejs]
disabled = true

[line_break]
disabled = true

[username]
style_user = "green"
format = "[@$user:]($style) "
show_always = false

[directory]
style = "blue"

[git_branch]
symbol = ""
style = "purple"
format = "[$symbol$branch]($style) "

[git_status]
style = "purple"
format = "([\\($all_status$ahead_behind\\) ]($style))"